const actionsTypes = {
  REQUEST_POKEMONS: 'REQUEST_POKEMONS',
  SUCCESS_POKEMONS: 'SUCCESS_POKEMONS',
  FAILURE_POKEMONS: 'FAILURE_POKEMONS',

  ADD_POKEMONS: 'ADD_POKEMONS',
  REMOVE_POKEMON: 'REMOVE_POKEMON',

  REQUEST_POKEMON: 'REQUEST_POKEMON',
  SUCCESS_POKEMON: 'SUCCESS_POKEMON',
  FAILURE_POKEMON: 'FAILURE_POKEMON',

  SEARCH_POKEMONS: 'SEARCH_POKEMONS',
  SUCCESS_SEARCH_POKEMONS: 'SUCCESS_SEARCH_POKEMONS',
  FAILURE_SEARCH_POKEMONS: 'FAILURE_SEARCH_POKEMONS',
};

export default actionsTypes;
